// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using dBanking.Infrastructure.DbContext;

#nullable disable

namespace dBanking.Infrastructure.Migrations.AppPostgresDb
{
    [DbContext(typeof(AppPostgresDbContext))]
    [Migration("20260114102413_AddDBMigration1")]
    partial class AddDBMigration1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.InboxState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("Consumed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<int>("ReceiveCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Received")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasAlternateKey("MessageId", "ConsumerId");

                    b.HasIndex("Delivered");

                    b.ToTable("InboxState");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.Property<long>("SequenceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SequenceNumber"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<string>("DestinationAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("EnqueueTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FaultAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Headers")
                        .HasColumnType("text");

                    b.Property<Guid?>("InboxConsumerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InboxMessageId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InitiatorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OutboxId")
                        .HasColumnType("uuid");

                    b.Property<string>("Properties")
                        .HasColumnType("text");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResponseAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("SentTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("SequenceNumber");

                    b.HasIndex("EnqueueTime");

                    b.HasIndex("ExpirationTime");

                    b.HasIndex("OutboxId", "SequenceNumber")
                        .IsUnique();

                    b.HasIndex("InboxMessageId", "InboxConsumerId", "SequenceNumber")
                        .IsUnique();

                    b.ToTable("OutboxMessage");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxState", b =>
                {
                    b.Property<Guid>("OutboxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("OutboxId");

                    b.HasIndex("Created");

                    b.ToTable("OutboxState");
                });

            modelBuilder.Entity("dBanking.Core.Entities.AuditRecord", b =>
                {
                    b.Property<Guid>("AuditRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("AfterJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("BeforeJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Environment")
                        .HasColumnType("text");

                    b.Property<Guid?>("RelatedEntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Source")
                        .HasColumnType("text");

                    b.Property<Guid?>("TargetEntityId")
                        .IsRequired()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("AuditRecordId");

                    b.HasIndex("Action");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("Timestamp");

                    b.HasIndex("EntityType", "TargetEntityId");

                    b.HasIndex("EntityType", "TargetEntityId", "Timestamp");

                    b.ToTable("AuditRecords", "public");

                    b.HasData(
                        new
                        {
                            AuditRecordId = new Guid("aaaabbbb-cccc-dddd-eeee-ffff00000001"),
                            Action = "CREATE",
                            Actor = "sub:rahul@aad",
                            AfterJson = "{\"customerId\":\"00112233-4455-6677-8899-aabbccddeeff\",\"status\":\"PENDING_KYC\"}",
                            CorrelationId = "corr-rahul-001",
                            EntityType = "Customer",
                            TargetEntityId = new Guid("00112233-4455-6677-8899-aabbccddeeff"),
                            Timestamp = new DateTimeOffset(new DateTime(2025, 12, 1, 10, 36, 30, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            AuditRecordId = new Guid("aaaabbbb-cccc-dddd-eeee-ffff00000002"),
                            Action = "CREATE",
                            Actor = "sub:rahul@aad",
                            AfterJson = "{\"kycCaseId\":\"aaaaaaaa-bbbb-cccc-dddd-eeeeffff0001\",\"status\":\"PENDING\"}",
                            CorrelationId = "corr-rahul-001",
                            EntityType = "KycCase",
                            TargetEntityId = new Guid("aaaaaaaa-bbbb-cccc-dddd-eeeeffff0001"),
                            Timestamp = new DateTimeOffset(new DateTime(2025, 12, 1, 10, 36, 50, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            AuditRecordId = new Guid("aaaabbbb-cccc-dddd-eeee-ffff00000003"),
                            Action = "UPDATE",
                            Actor = "system:closure",
                            AfterJson = "{\"customerId\":\"99998888-7777-6666-5555-444433332222\",\"status\":\"CLOSED\"}",
                            BeforeJson = "{\"customerId\":\"99998888-7777-6666-5555-444433332222\",\"status\":\"VERIFIED\"}",
                            CorrelationId = "corr-closure-amit-01",
                            EntityType = "Customer",
                            TargetEntityId = new Guid("99998888-7777-6666-5555-444433332222"),
                            Timestamp = new DateTimeOffset(new DateTime(2025, 12, 5, 14, 0, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("dBanking.Core.Entities.Customer", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Dob")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CustomerId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Phone");

                    b.HasIndex("FirstName", "LastName", "Dob");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = new Guid("00112233-4455-6677-8899-aabbccddeeff"),
                            CreatedAt = new DateTime(2025, 12, 1, 10, 30, 0, 0, DateTimeKind.Utc),
                            Dob = new DateOnly(1994, 4, 11),
                            Email = "rahul.sharma@example.com",
                            FirstName = "Rahul",
                            LastName = "Sharma",
                            Phone = "+91-9876543210",
                            Status = 0
                        },
                        new
                        {
                            CustomerId = new Guid("11112222-3333-4444-5555-666677778888"),
                            CreatedAt = new DateTime(2025, 11, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            Dob = new DateOnly(1992, 6, 25),
                            Email = "neha.kulkarni@example.com",
                            FirstName = "Neha",
                            LastName = "Kulkarni",
                            Phone = "+91-9822001122",
                            Status = 1,
                            UpdatedAt = new DateTime(2025, 11, 20, 9, 15, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            CustomerId = new Guid("99998888-7777-6666-5555-444433332222"),
                            CreatedAt = new DateTime(2025, 10, 10, 11, 45, 0, 0, DateTimeKind.Utc),
                            Dob = new DateOnly(1988, 1, 3),
                            Email = "amit.patil@example.com",
                            FirstName = "Amit",
                            LastName = "Patil",
                            Phone = "+91-9812345678",
                            Status = 2,
                            UpdatedAt = new DateTime(2025, 12, 5, 14, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("dBanking.Core.Entities.KycCase", b =>
                {
                    b.Property<Guid>("KycCaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CheckedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ConsentText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("EvidenceRefsJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("ProviderRef")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("KycCaseId");

                    b.HasIndex("CustomerId", "Status");

                    b.ToTable("KycCases");

                    b.HasData(
                        new
                        {
                            KycCaseId = new Guid("aaaaaaaa-bbbb-cccc-dddd-eeeeffff0001"),
                            AcceptedAt = new DateTime(2025, 12, 1, 10, 35, 0, 0, DateTimeKind.Utc),
                            ConsentText = "I consent to eKYC verification for account onboarding.",
                            CreatedAt = new DateTime(2025, 12, 1, 10, 36, 0, 0, DateTimeKind.Utc),
                            CustomerId = new Guid("00112233-4455-6677-8899-aabbccddeeff"),
                            EvidenceRefsJson = "[\"doc-POI-123\",\"doc-POA-456\"]",
                            Status = 0
                        },
                        new
                        {
                            KycCaseId = new Guid("aaaaaaaa-bbbb-cccc-dddd-eeeeffff0002"),
                            AcceptedAt = new DateTime(2025, 11, 15, 8, 5, 0, 0, DateTimeKind.Utc),
                            CheckedAt = new DateTime(2025, 11, 15, 9, 10, 0, 0, DateTimeKind.Utc),
                            ConsentText = "I consent to eKYC verification for account onboarding.",
                            CreatedAt = new DateTime(2025, 11, 15, 8, 6, 0, 0, DateTimeKind.Utc),
                            CustomerId = new Guid("11112222-3333-4444-5555-666677778888"),
                            EvidenceRefsJson = "[\"doc-POI-777\",\"doc-POA-888\"]",
                            ProviderRef = "kyc-prov-789",
                            Status = 1
                        });
                });

            modelBuilder.Entity("dBanking.Core.Entities.KycCase", b =>
                {
                    b.HasOne("dBanking.Core.Entities.Customer", "Customer")
                        .WithMany("KycCases")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("dBanking.Core.Entities.Customer", b =>
                {
                    b.Navigation("KycCases");
                });
#pragma warning restore 612, 618
        }
    }
}
